### ISSUE TITLE
Auto-generated project fails to start

### ISSUE THREAD

**Issue by briwilcox** [OfficeDev/generator-office#263]
As far as I know I didn't miss a step, following MSDN docs here: https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial

Support URL is commented out in the manifest.xml otherwise the app was created with default choices. npm start is being launched from power shell. 

Sanitized log dump:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.9
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart my-app@0.1.0
6 info start my-app@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info my-app@0.1.0 Failed to exec start script
9 error my-app@0.1.0 start: `rimraf dist && concurrently "npm run tsc" "npm run copy" "npm run server"`
9 error Exit status 1
10 error Failed at the my-app@0.1.0 start script.
10 error This is most likely a problem with the my-app package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     rimraf dist && concurrently "npm run tsc" "npm run copy" "npm run server"
10 error You can get their info via:
10 error     npm owner ls my-app
10 error There is likely additional logging output above.
11 error System Windows_NT 10.0.16299
12 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error cwd C:\Users\redacted\OfficeProject\my-app
14 error node -v v8.9.1
15 error npm -v 1.4.9
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

```

**Comment by briwilcox** [comment]
Upgraded to node v9.1.0 and tried executing from powershell and cmd but still no luck.

**Comment by briwilcox** [comment]
I solved my own issue, I simply had to manually install the npm packages the project depended on and it is working fine now.

Either [the tutorial](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial) should be updated to reflect that yeoman won't install these dependencies for you or if that is a bug it should be fixed.

**Comment by jesspetersen** [comment]
What packages did you need to install, @briwilcox ? I'm also having trouble with this.

**Comment by LouMM** [comment]
Thank you @briwilcox ! The generator should install all the packages after laying down all of the scaffolding. Can you confirm on the latest package this is still not working? I just tried it and it seems to be working for Outlook. https://www.npmjs.com/package/generator-office

**Comment by TCourtneyOwen** [comment]
@briwilcox This is quite an old issue, and we haven't heard of any similar issues in the numerous yo office updates we have published since this issue was originally opened. Please update to the latest version of yo office (1.3.0) to see if this fixes the issue. If not, please reopen the issue and we will investigate further.

Thanks,

Courtney
