### ISSUE TITLE
`yo office` fail with EACCES permission denied

### ISSUE THREAD

**Issue by dotSlashLu** [OfficeDev/generator-office#340]
The mode of the file is 0777, yet `yo office` always fails with permission denied.
```
root@jarvis: ~/on
# yo office                                                                                                                                                                         [13:13:52]
/root/.nvm/versions/node/v8.3.0/lib/node_modules/yo/node_modules/conf/index.js:128
                        throw err;
                        ^

Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Conf.get store [as store] (/root/.nvm/versions/node/v8.3.0/lib/node_modules/yo/node_modules/conf/index.js:108:18)
    at Conf.get (/root/.nvm/versions/node/v8.3.0/lib/node_modules/yo/node_modules/conf/index.js:47:26)
    at Insight.get optOut [as optOut] (/root/.nvm/versions/node/v8.3.0/lib/node_modules/yo/node_modules/insight/lib/index.js:52:22)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.3.0/lib/node_modules/yo/lib/cli.js:197:47)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
FAIL: 1

root@jarvis: ~/on
# ls -al /root/.config/insight-nodejs/insight-yo.json                                                                                                                               [13:13:56]
-rwxrwxrwx 1 root root 29 Jul 20 13:13 /root/.config/insight-nodejs/insight-yo.json
```

**Comment by TCourtneyOwen** [comment]
Are you running Yo Office as an administrator from the command prompt?  If not, then please give this a try and let me know how it goes.

Thanks,

Courtney

**Comment by dotSlashLu** [comment]
Hi Courtney. Yes, actually I was on a Linux box using root. Is Linux unsupported? If so please close this issue, I tried it later on Windows and it worked well. And it seems more like a problem of yeoman anyway...

**Comment by TCourtneyOwen** [comment]
Linux is supported so I will need to look into this.  In fact, we have a battery of tests that we run against Linux, and we haven't hit any failures in our tests recently. Are you trying to run yo office in the GIT Bash?

Thanks,

Courtney

**Comment by ThorstenHans** [comment]
Hey @dotSlashLu,

I've tested the following combination

- ubuntu `18.04.1`
- nvm `0.33.11`
- node `8.3.0` same as you've installed according to your snippet
- yo `2.0.5`
- generator-office `1.1.18`

I've installed `nvm` as regular user (no sudoing here) which means node installations will live inside of my home folder. That said, installing node modules globally will also work without `sudo`.

I can remember, that I saw errors like the one you're facing on a attendees machine during a workshop. The guy had installed `nvm` using `sudo`, if I recall correctly. 

So It would be great if you can verify and share a few more insights about installed versions of the packages mentioned above on your system.

Thanks,

Thorsten

**Comment by dotSlashLu** [comment]
@ThorstenHans thanks for your thorough investigation. I'll try with a non-root account tomorrow and let you know if it works.

**Comment by TCourtneyOwen** [comment]
@dotSlashLu This is quite an old issue, and we haven't heard of any similar issues in the numerous yo office updates we have published since this issue was originally opened. Please update to the latest version of yo office (1.3.0) to see if this fixes the issue. If not, please reopen the issue and we will investigate further.

Thanks,

Courtney

**Comment by SWei1234** [comment]
Hi @TCourtneyOwen 
I also have met this problem on linux.
it shows: `/usr/local/lib/node_modules/yo/node_modules/write-file-atomic/index.js:236
    throw err
    ^

Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json.1813609801'
`
But it works fine on Windows. I'm on centOS 7. 
Thanks

**Comment by TCourtneyOwen** [comment]
@SWei1234 What version of generator-office are you running?  The latest version is 1.7.9.  I recall that we made a fix this issue, but maybe you a running into a different issue. If indeed you are running an older version of generator-office, can you please try updating to the most recent version?

Thanks,

Courtney

**Comment by SWei1234** [comment]
Hi @TCourtneyOwen 
Using 'yo --version' get version is 3.1.1. 
And I tried get generate by using 'https://github.com/OfficeDev/generator-office.git' then build.
But the problem still exist.
(Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json.4269800691')
Any idea?

Thanks
